# This is the global configuration file for Workflow

# If the service is used by a component alone, it needs to be configured inside the component.
# Refer to rabbitmqUrl and databaseUrl of the controller component. 
# If the service is dependent on multiple components and there is state synchronization,
# it needs to be configured separately, such as storage and influxdb.

global:
  # Admin email, used for each component to send email to administrator
  email: "drycc@drycc.cc"

  # Set the location of Workflow's Object Storage
  #
  # Valid values are:
  # - on-cluster: Run drycc storage within the Kubernetes cluster
  # - off-cluster: Run Storage outside the Kubernetes cluster (Compatible with s3 API)
  storageLocation: "on-cluster"

  # Set the location of Workflow's PostgreSQL database
  #
  # Valid values are:
  # - on-cluster: Run PostgreSQL within the Kubernetes cluster (credentials are generated
  #   automatically; backups are sent to object storage
  #   configured above)
  # - off-cluster: Run PostgreSQL outside the Kubernetes cluster
  databaseLocation: "on-cluster"

  # Set the location of Workflow's Redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in redis section)
  redisLocation: "on-cluster"
  # Set the location of Workflow's rabbitmq instance
  # Valid values are:
  # - on-cluster: Run Rabbitmq within the Kubernetes cluster
  # - off-cluster: Run Rabbitmq outside the Kubernetes cluster (configure in controller section)
  rabbitmqLocation: "on-cluster"
  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdbLocation: "on-cluster"
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafanaLocation: "on-cluster"

  # Set the location of Workflow's Registry
  #
  # Valid values are:
  # - on-cluster: Run registry within the Kubernetes cluster
  # - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,quay.io,self-hosted)
  registryLocation: "on-cluster"
  # Prefix for the imagepull secret created when using private registry
  registrySecretPrefix: "private-registry"
  # The host port to which registry proxy binds to
  registryProxyPort: 5555

  # Enable usage of RBAC authorization mode
  #
  # Valid values are:
  # - true: all RBAC-related manifests will be installed (in case your cluster supports RBAC)
  # - false: no RBAC-related manifests will be installed
  rbac: true
  # Please check `kubernetes.io/ingress.class`
  # The cert-manager component must be installed
  # If you want to use HTTPSEnforced or allowlist functions, you must specify:
  # - nginx
  # - traefik
  # Only the above options have been supported so far
  ingressClass: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
  # The publicly resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether certManagerEnabled is true to automatically generate drycc certificates
  certManagerEnabled: true
  # Set the location of Workflow's passport
  #
  # Valid values are:
  # - on-cluster: Run passport within the Kubernetes cluster
  # - off-cluster: Use passport outside the Kubernetes cluster
  passportLocation: "on-cluster"

storage:
  # bucket lookup supported by the server.
  # Valid options are '[dns, path]'
  # When the storage is off-cluster, this value can be set
  # Otherwise, Hard coded as `path`
  lookup: "path"
  # health check url is only available in off-cluster storage
  health: ""
  # endpoint configuration is only available in off-cluster storage
  endpoint: ""
  # If storage is off-cluster, accesskey and secretkey must be specified
  # Otherwise, they are generated randomly, if they are empty
  accesskey: ""
  secretkey: ""
  # The following three bucket name parameters are valid only in cluster-off
  # In the case of cluster-on, they are hard coded and named: builder, registry
  builderBucket: "drycc-builder-bucket"
  registryBucket: "drycc-registry-bucket"
  # Configure the following ONLY if you want persistence for on-cluster storage
  persistence:
    enabled: false # Set to true to enable persistence
    accessMode: ReadWriteOnce
    size: 5Gi # PVC size
    ## storage data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    ## Storage class of PV to bind. By default it looks for standard storage class.
    ## If the PV uses a different storage class, specify that here.
    storageClass: ""
    volumeName: ""

# Set the default (global) way of how Application (your own) images are
# pulled from within the Controller.
# This can be configured per Application as well in the Controller.
#
# This affects pull apps and git push apps
#
# Values values are:
# - Always
# - IfNotPresent
builder:
  service:
    # Service type default to ClusterIP, the entrance will be taken over by router.
    type: ClusterIP
    # If service.type is not set to NodePort, the following statement will be ignored.
    nodePort: ""

controller:
  appImagePullPolicy: "IfNotPresent"
  # Possible values are:
  # enabled - allows for open registration
  # disabled - turns off open registration
  # admin_only - allows for registration by an admin only.
  registrationMode: "admin_only"
  # Set storageClassName, It is used for application mount.
  appStorageClass: "drycc-storage"
  # Set controller deployment  replicas
  replicas: 1
  # Set celery replicas
  celeryReplicas: 1
  ## databaseUrl and databaseReplicaUrl are will no longer use the built-in database component
  databaseUrl: ""
  databaseReplicaUrl: ""
  # Configuring this will no longer use the built-in rabbitmq component
  rabbitmqUrl: ""

database:
  # The following parameters are configured only when using an on-cluster Database instance
  # If left empty they will be generated using randAlphaNum
  username: ""
  password: ""
  persistence:
    enabled: false # Set to true to enable persistence
    accessMode: ReadWriteOnce
    size: 5Gi # PVC size
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    ## Storage class of PV to bind. By default it looks for standard storage class.
    ## If the PV uses a different storage class, specify that here.
    storageClass: ""
    volumeName: ""

redis:
  # The addrs parameters are configured only when using an off-cluster Redis instance
  addrs: "" # A list of clusters: "127.0.0.1:7001/1,127.0.0.2:7002/1"
  password: "redis password" # "" == no password
  # The following parameters are configured only when using an on-cluster Redis instance
  replicas: 1
  persistence:
    enabled: false # Set to true to enable persistence
    size: 5Gi
    storageClass: ""

rabbitmq:
  # The following parameters are configured only when using an on-cluster Rabbitmq instance
  # If left empty they will be generated using randAlphaNum
  username: ""
  password: ""
  # GCP PDs and EBS volumes are supported only
  persistence:
    enabled: false # Set to true to enable persistence
    size: 5Gi # PVC size
    ## rabbitmq data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    ## Storage class of PV to bind. By default it looks for standard storage class.
    ## If the PV uses a different storage class, specify that here.
    storageClass: ""

influxdb:
  # URL configuration is only available in off-cluster Influx database
  url: "http://my.influx.url:8086"
  bucket: "kubernetes"
  org: "org"
  # If influxdb is off-cluster, it must be specified
  # Otherwise, it is generated randomly, if it is empty
  token: ""
  # Configure the following is only available in on-cluster Influx database
  user: "admin"
  password: "admin123"
  retention: "30d"
  # GCP PDs and EBS volumes are supported only
  persistence:
    enabled: false # Set to true to enable persistence
    accessMode: ReadWriteOnce
    size: 5Gi # PVC size
    ## influxdb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    ## Storage class of PV to bind. By default it looks for standard storage class.
    ## If the PV uses a different storage class, specify that here.
    storageClass: ""
    volumeName: ""

fluentd:
  syslog:
    # Configure the following ONLY if using Fluentd to send log messages to both
    # the Logger component and external syslog endpoint
    # external syslog endpoint url
    host: ""
    # external syslog endpoint port
    port: ""

monitor:
  grafana:
    # Configure the following ONLY if you want persistence for on-cluster grafana
    # GCP PDs and EBS volumes are supported only
    persistence:
      enabled: false # Set to true to enable persistence
      accessMode: ReadWriteOnce
      size: 5Gi # PVC size
      ## influxdb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      ## Storage class of PV to bind. By default it looks for standard storage class.
      ## If the PV uses a different storage class, specify that here.
      storageClass: ""
      volumeName: ""

registry:
  # The host parameters is configured only when using an off-cluster Registry instance
  host: ""
  # The following organization parameters are valid only in cluster-off
  # In the case of cluster-on, the value is app name, which is dynamically assigned by builder.
  organization: ""
  username: ""
  password: ""
  # The redirect parameters is configured only when using an on-cluster Registry instance
  # The subsection provides configuration for managing redirects from content backends.
  # For backends that support it, redirecting is disabled by default.
  redirect: "false"

passport:
  # The following parameters are configured only when using an on-cluster passport
  # Set passport deployment replicas
  replicas: 1
  ## databaseUrl and databaseReplicaUrl are will no longer use the built-in database component
  databaseUrl: ""
  databaseReplicaUrl: ""

# acme configuration takes effect if and only if certManagerEnabled is true
acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  #  EAB credentials
  externalAccountBinding:
    keyID: ""
    keySecret: ""