# This is the global configuration file for Workflow

# If the service is used by a component alone, it needs to be configured inside the component.
# If the service is dependent on multiple components and there is state synchronization,
# it needs to be configured separately, such as storage.

global:
  # Admin email, used for each component to send email to administrator
  email: "drycc@drycc.cc"
  # The publicly resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether certManagerEnabled is true to automatically generate drycc certificates
  certManagerEnabled: false

builder:
  service:
    # Service type default to ClusterIP, the entrance will be taken over by router.
    type: ClusterIP
    # If service.type is not set to NodePort, the following statement will be ignored.
    nodePort: ""

# Drycc Gateway is a gateway chart that integrates cert-manager.
gateway:
  # GatewayClass is cluster-scoped resource defined by the infrastructure provider.
  gatewayClass: ""
  # acme configuration takes effect if and only if certManagerEnabled is true
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #  EAB credentials
    externalAccountBinding:
      keyID: ""
      keySecret: ""

fluentbit:
  # Interval to flush output (seconds)
  flush: 5

controller:
  appImagePullPolicy: "IfNotPresent"
  # Possible values are:
  # enabled - allows for open registration
  # disabled - turns off open registration
  # admin_only - allows for registration by an admin only.
  registrationMode: "admin_only"
  # Set app gateway, It is used for application gateway.
  appGatewayClass: ""
  # Set storageClassName, It is used for application mount.
  appStorageClass: "longhorn"
  # Set controller deployment  replicas
  replicas: 1
  # Set celery replicas
  celeryReplicas: 1
  ## databaseUrl and databaseReplicaUrl are will no longer use the built-in database component
  databaseUrl: ""
  databaseReplicaUrl: ""

valkey:
  enabled: true
  # The addrs parameters are configured only when using an off-cluster Valkey instance
  addrs: "" # A list of clusters: "127.0.0.1:7001/1,127.0.0.2:7002/1"
  password: "valkey password" # "" == no password
  # The following parameters are configured only when using an on-cluster Valkey instance
  replicas: 3
  persistence:
    enabled: false # Set to true to enable persistence
    size: 5Gi
    storageClass: ""

storage:
  enabled: true
  # The following parameters are general parameters
  accesskey: ""
  secretkey: ""
  persistence:
    enabled: false
    size: 5Gi
    storageClass: ""

grafana:
  enabled: true
  persistence:
    enabled: false
    size: 5Gi
    storageClass: ""

registry:
  enabled: true
  username: ""
  password: ""
  # The redirect parameters is configured only when using an on-cluster Registry instance
  # The subsection provides configuration for managing redirects from content backends.
  # For backends that support it, redirecting is disabled by default.
  redirect: "false"
  # host port for the registry proxy in the daemonset
  proxy:
    port: 5555

passport:
  enabled: true
  # The following parameters are configured only when using an on-cluster passport
  # Set passport deployment replicas
  replicas: 1
  ## databaseUrl and databaseReplicaUrl are will no longer use the built-in database component
  databaseUrl: ""
  databaseReplicaUrl: ""

database:
  enabled: true
  # The following parameters are configured only when using an on-cluster Database instance
  # The username and password to be used by the on-cluster database.
  # If left empty they will be generated
  # The user name should be set to lowercase letters 
  superuser: "postgres"
  superuserPassword: ""
  replicator: "standby"
  replicatorPassword: ""
  user: ""
  password: ""
  persistence:
    enabled: false
    size: 5Gi
    storageClass: ""

victoriametrics:
  enabled: true
  ## victoriametrics vmagent configuration
  ##
  vmagent:
    replicas: 3
    persistence:
      enabled: false
      size: 5Gi
      storageClass: ""

  ## victoriametrics vminsert configuration
  ##
  vminsert:
    replicas: 3

  ## victoriametrics vmselect configuration
  ##
  vmselect:
    replicas: 3

  ## victoriametrics vmstorage configuration
  ##
  vmstorage:
    replicas: 3
    persistence:
      enabled: false
      size: 5Gi
      storageClass: ""

  ## node-exporter configuration##
  nodeExporter:
    enabled: true
  ## kube-state-metrics configuration
  ##
  kubeStateMetrics:
    enabled: true
