# This is the global configuration file for Workflow

global:
  # Set the storage backend
  #
  # Valid values are:
  # - s3: Store persistent data in AWS S3 (configure in S3 section)
  # - azure: Store persistent data in Azure's object storage
  # - gcs: Store persistent data in Google Cloud Storage
  # - oss: Store persistent data in Aliyun OSS
  # - minio: Store persistent data on in-cluster Minio server
  storage: minio

  # Set the location of Workflow's PostgreSQL database
  #
  # Valid values are:
  # - on-cluster: Run PostgreSQL within the Kubernetes cluster (credentials are generated
  #   automatically; backups are sent to object storage
  #   configured above)
  # - off-cluster: Run PostgreSQL outside the Kubernetes cluster (configure in database section)
  database_location: "on-cluster"

  # Set the location of Workflow's logger-specific Redis instance
  #
  # Valid values are:
  # - on-cluster: Run Redis within the Kubernetes cluster
  # - off-cluster: Run Redis outside the Kubernetes cluster (configure in loggerRedis section)
  logger_redis_location: "on-cluster"

  # Set the location of Workflow's influxdb cluster
  #
  # Valid values are:
  # - on-cluster: Run Influxdb within the Kubernetes cluster
  # - off-cluster: Influxdb is running outside of the cluster and credentials and connection information will be provided.
  influxdb_location: "on-cluster"
  # Set the location of Workflow's grafana instance
  #
  # Valid values are:
  # - on-cluster: Run Grafana within the Kubernetes cluster
  # - off-cluster: Grafana is running outside of the cluster
  grafana_location: "on-cluster"

  # Set the location of Workflow's Registry
  #
  # Valid values are:
  # - on-cluster: Run registry within the Kubernetes cluster
  # - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,quay.io,self-hosted)
  # - ecr: Use Amazon's ECR
  # - gcr: Use Google's GCR
  registry_location: "on-cluster"
  # The host port to which registry proxy binds to
  host_port: 5555
  # Prefix for the imagepull secret created when using private registry
  secret_prefix: "private-registry"
  # Experimental feature to use Kubernetes ingress instead of Workflow's drycc-router.
  #
  # Valid values are:
  # - true: drycc-router will not be deployed. Workflow will not be usable until a Kubernetes ingress controller is installed.
  # - false: drycc-router will be deployed (default).
  use_native_ingress: false
  # If the Kubernetes cluster uses CNI
  # use_cni: true
  # Set the `listen` variable for registry-proxy's NGINX
  #
  # Valid values are:
  # - 80: If the Kubernetes cluster run on GKE or AWS, or uses flannel or kubenet as a pod network
  # - 127.0.0.1:5555: If the Kubernetes cluster uses CNI
  #
  # In case of CNI you can not use `hostPort` notation due to https://github.com/kubernetes/kubernetes/issues/23920
  # registry_proxy_bind_addr: "80"

  # Enable usage of RBAC authorization mode
  #
  # Valid values are:
  # - true: all RBAC-related manifests will be installed (in case your cluster supports RBAC)
  # - false: no RBAC-related manifests will be installed
  use_rbac: true


s3:
  # Your AWS access key. Leave it empty if you want to use IAM credentials.
  accesskey: ""
  # Your AWS secret key. Leave it empty if you want to use IAM credentials.
  secretkey: ""
  # Any S3 region
  endpoint: "your-s3-endpoint"
  # Your buckets.
  builder_bucket: "your-builder-bucket-name"
  registry_bucket: "your-registry-bucket-name"
  database_bucket: "your-database-bucket-name"

oss:
  accesskey: ""
  secretkey: ""
  endpoint: "your-oos-endpoint"
  builder_bucket: "your-builder-bucket-name"
  registry_bucket: "your-registry-bucket-name"
  database_bucket: "your-database-bucket-name"

azure:
  accesskey: "YOUR ACCOUNT NAME"
  secretkey: "YOUR ACCOUNT KEY"
  endpoint: "your-azure-endpoint"
  builder_bucket: "your-builder-container-name"
  registry_bucket: "your-registry-container-name"
  database_bucket: "your-database-container-name"

gcs:
  # key_json is expanded into a JSON file on the remote server. It must be
  # well-formatted JSON data.
  accesskey: "your accessKey for minio gateway"
  secretkey: "your secretkey for minio gateway"
  key_json: <base64-encoded JSON data>
  projectid: "your-gcs-projectid"
  builder_bucket: "your-builder-bucket-name"
  registry_bucket: "your-registry-bucket-name"
  database_bucket: "your-database-bucket-name"

minio:
  accesskey: "8TZRY2JRWMPT6UMXR6I5"
  secretkey: "gbstrOvotMMcg2sMfGUhA5a6Et/EI5ALtIHsobYk"
  builder_bucket: "0fad60517a9e4225a07d77d7b9b58629"
  registry_bucket: "c2da53f11c7a455db35797c3ba625d80"
  database_bucket: "e95eb5c54c3a4047abe5269a68fa9a67"

# Set the default (global) way of how Application (your own) images are
# pulled from within the Controller.
# This can be configured per Application as well in the Controller.
#
# This affects pull apps and git push (slugrunner images) apps
#
# Values values are:
# - Always
# - IfNotPresent
controller:
  app_pull_policy: "IfNotPresent"
  # Possible values are:
  # enabled - allows for open registration
  # disabled - turns off open registration
  # admin_only - allows for registration by an admin only.
  registration_mode: "admin_only"
  # The publicly resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platform_domain: ""

database:
  # The username and password to be used by the on-cluster database.
  # If left empty they will be generated using randAlphaNum
  username: ""
  password: ""
  # Configure the following ONLY if using an off-cluster PostgreSQL database
  postgres:
    name: "database name"
    username: "database username"
    password: "database password"
    host: "database host"
    port: "database port"

redis:
  # Configure the following ONLY if using an off-cluster Redis instance for logger
  db: "0"
  host: "redis host"
  port: "redis port"
  password: "redis password" # "" == no password

fluentd:
  syslog:
    # Configure the following ONLY if using Fluentd to send log messages to both
    # the Logger component and external syslog endpoint
    # external syslog endpoint url
    host: ""
    # external syslog endpoint port
    port: ""

monitor:
  grafana:
    user: "admin"
    password: "admin"
    # Configure the following ONLY if you want persistence for on-cluster grafana
    # GCP PDs and EBS volumes are supported only
    persistence:
      enabled: false # Set to true to enable persistence
      size: 5Gi # PVC size

  influxdb:
    # Configure the following ONLY if using an off-cluster Influx database
    url: "my.influx.url"
    database: "kubernetes"
    user: "user"
    password: "password"
    # Configure the following ONLY if you want persistence for on-cluster influxdb
    # GCP PDs and EBS volumes are supported only
    persistence:
      enabled: false # Set to true to enable persistence
      size: 20Gi # PVC size

registry-token-refresher:
  # Time in minutes after which the token should be refreshed.
  # Leave it empty to use the default provider time.
  token_refresh_time: ""
  off_cluster_registry:
    hostname: ""
    organization: ""
    username: ""
    password: ""
  ecr:
    # Your AWS access key. Leave it empty if you want to use IAM credentials.
    accesskey: ""
    # Your AWS secret key. Leave it empty if you want to use IAM credentials.
    secretkey: ""
    # Any S3 region
    region: "us-west-2"
    registryid: ""
    hostname: ""
  gcr:
    key_json: <base64-encoded JSON data>
    hostname: ""

router:
  dhparam: ""
  # Any custom router annotations(https://github.com/drycc/router#annotations)
  # which need to be applied can be specified as key-value pairs under "deployment_annotations"
  deployment_annotations:
    #<example-key>: <example-value>

  # Any custom annotations for k8s services like http://kubernetes.io/docs/user-guide/services/#ssl-support-on-aws
  # which need to be applied can be specified as key-value pairs under "service_annotations"
  service_annotations:
    #<example-key>: <example-value>

  service:
    # Service type default to LoadBalancer
    type: LoadBalancer
    # If service.type is not set to NodePort, the following statement will be ignored.
    nodePort:
      builder: ""
      http: ""
      https: ""
      healthz: ""

workflow-manager:
  versions_api_url: https://versions.drycc.cc
  doctor_api_url: https://doctor.drycc.cc
