apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-keyfile
  labels:
    heritage: drycc
  annotations:
    drycc.cc/objectstorage: "{{ .Values.global.storage }}"
type: Opaque
data:
{{ if eq .Values.global.storage "gcs"}}
  accesskey: {{.Values.gcs.accesskey | b64enc }}
  secretkey: {{ .Values.gcs.secretkey | b64enc }}
  key.json: {{.Values.gcs.key_json}}
  projectid: {{ .Values.gcs.projectid | b64enc }}
  builder-bucket: {{.Values.gcs.builder_bucket | b64enc }}
  registry-bucket: {{.Values.gcs.registry_bucket | b64enc }}
  database-bucket: {{.Values.gcs.database_bucket | b64enc }}
{{ else if eq .Values.global.storage "azure"}}
  accesskey: {{.Values.azure.accesskey | b64enc }}
  secretkey: {{ .Values.azure.secretkey | b64enc }}
  endpoint: {{ .Values.azure.endpoint | b64enc }}
  builder-bucket: {{ .Values.azure.builder_bucket | b64enc }}
  registry-bucket: {{ .Values.azure.registry_bucket | b64enc }}
  database-bucket: {{ .Values.azure.database_bucket | b64enc }}
{{ else if eq .Values.global.storage "s3"}}
  accesskey: {{ .Values.s3.accesskey | b64enc }}
  secretkey: {{ .Values.s3.secretkey | b64enc }}
  endpoint: {{ .Values.s3.endpoint | b64enc }}
  builder-bucket: {{ .Values.s3.builder_bucket | b64enc }}
  registry-bucket: {{.Values.s3.registry_bucket | b64enc }}
  database-bucket: {{.Values.s3.database_bucket | b64enc }}
{{ else if eq .Values.global.storage "oss"}}
  accesskey: {{ .Values.oss.accesskey | b64enc }}
  secretkey: {{ .Values.oss.secretkey | b64enc }}
  endpoint: {{ .Values.oss.endpoint | b64enc }}
  builder-bucket: {{ .Values.oss.builder_bucket | b64enc }}
  registry-bucket: {{.Values.oss.registry_bucket | b64enc }}
  database-bucket: {{.Values.oss.database_bucket | b64enc }}
{{else if eq .Values.global.storage "minio"}}
  accesskey: {{ .Values.minio.accesskey | b64enc }}
  secretkey: {{ .Values.minio.secretkey | b64enc }}
  builder-bucket: {{ .Values.minio.builder_bucket | b64enc }}
  registry-bucket: {{.Values.minio.registry_bucket | b64enc }}
  database-bucket: {{.Values.minio.database_bucket | b64enc }}
{{ end }}
