{{- if ne .Values.global.registryLocation "on-cluster" }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    heritage: drycc
  annotations:
    drycc.cc/registry-location: "{{ .Values.global.registryLocation }}"
type: Opaque
data:
  hostname: {{ .Values.registry.hostname | b64enc }}
  organization: {{ .Values.registry.organization | b64enc }}
  username: {{ .Values.registry.username | b64enc }}
  password: {{ .Values.registry.password | b64enc }}
{{- end }}
