#
# NOTE: titles need to be capitalized here to work around MkDocs automatically downcasing title
# names
#
site_name: Drycc Workflow Documentation
site_url: https://drycc.cc/docs/workflow
nav:
  - Home: index.md
  - Quick Start:
    - Overview: quickstart/index.md
    - Install CLI Tools: quickstart/install-cli-tools.md
    - AWS:
      - Boot: quickstart/provider/aws/boot.md
      - DNS: quickstart/provider/aws/dns.md
      - Install Workflow: quickstart/provider/aws/install-aws.md
    - Azure:
      - Boot: quickstart/provider/azure-acs/boot.md
      - DNS: quickstart/provider/azure-acs/dns.md
      - Install Workflow: quickstart/provider/azure-acs/install-azure-acs.md
    - GKE:
      - Boot: quickstart/provider/gke/boot.md
      - DNS: quickstart/provider/gke/dns.md
      - Install Workflow: quickstart/provider/gke/install-gke.md
    - Minikube:
      - Boot: quickstart/provider/minikube/boot.md
      - DNS: quickstart/provider/minikube/dns.md
      - Install Workflow: quickstart/provider/minikube/install-minikube.md
    - Deploy Your First App: quickstart/deploy-an-app.md
  - Understanding Workflow:
    - Concepts: understanding-workflow/concepts.md
    - Architecture: understanding-workflow/architecture.md
    - Components: understanding-workflow/components.md
  - Installing Workflow:
    - System Requirements: installing-workflow/system-requirements.md
    - Installing Ingress: installing-workflow/ingress.md
    - Installing Workflow: installing-workflow/index.md
    - Configuring Object Storage: installing-workflow/configuring-object-storage.md
    - Configuring Postgres: installing-workflow/configuring-postgres.md
    - Configuring the Registry: installing-workflow/configuring-registry.md
    - Chart Provenance: installing-workflow/chart-provenance.md
  - Users:
    - Command Line Interface: users/cli.md
    - Users and Registration: users/registration.md
    - SSH Keys: users/ssh-keys.md
  - Applications:
    - Deploying Apps: applications/deploying-apps.md
    - Buildpacks: applications/using-buildpacks.md
    - Dockerfiles: applications/using-dockerfiles.md
    - Docker Images: applications/using-docker-images.md
    - Managing App Processes: applications/managing-app-processes.md
    - Managing App Configuration: applications/managing-app-configuration.md
    - Managing App Lifecycle: applications/managing-app-lifecycle.md
    - Managing App Volumes: applications/managing-app-volumes.md
    - Managing App Resources: applications/managing-app-resources.md
    - Inter-app Communication: applications/inter-app-communication.md
    - Resource Limits: applications/managing-resource-limits.md
    - Domains and Routing: applications/domains-and-routing.md
    - SSL Certificates: applications/ssl-certificates.md
  - Managing Workflow:
    - Tuning Component Settings: managing-workflow/tuning-component-settings.md
    - Configuring DNS: managing-workflow/configuring-dns.md
    - Deploy Hooks: managing-workflow/deploy-hooks.md
    - Platform Logging: managing-workflow/platform-logging.md
    - Platform Monitoring: managing-workflow/platform-monitoring.md
    - Production Deployments: managing-workflow/production-deployments.md
    - Upgrading Workflow: managing-workflow/upgrading-workflow.md
    - Extending Workflow: managing-workflow/extending-workflow.md
  - Troubleshooting:
    - Troubleshooting Workflow: troubleshooting/index.md
    - Troubleshooting using Kubectl: troubleshooting/kubectl.md
    - Troubleshooting Applications: troubleshooting/applications.md
  - Roadmap:
    - Planning Process: roadmap/planning-process.md
    - Roadmap: roadmap/roadmap.md
    - Releases: roadmap/releases.md
  - Contributing:
    - Overview: contributing/overview.md
    - Design Documents: contributing/design-documents.md
    - Development Environment: contributing/development-environment.md
    - Testing: contributing/testing.md
    - Submitting a Pull Request: contributing/submitting-a-pull-request.md
    - Community: contributing/community.md
    - Triaging Issues: contributing/triaging-issues.md
    - Conduct: contributing/conduct.md
    - Maintainers: contributing/maintainers.md
  - Reference Guide:
    - Creating a Self-Signed SSL Certificate: reference-guide/creating-a-self-signed-ssl-certificate.md
    - Terms: reference-guide/terms.md
    # FIXME (bacongobbler): our custom drycc theme only supports a toctree depth of 2 due to css issues
    - Controller API v2.0: reference-guide/controller-api/v2.0.md
    - Controller API v2.1: reference-guide/controller-api/v2.1.md
    - Controller API v2.2: reference-guide/controller-api/v2.2.md
    - Controller API v2.3: reference-guide/controller-api/v2.3.md
  - Changelogs:
    - v1.3.0: changelogs/v1.3.0.md
    - v1.2.0: changelogs/v1.2.0.md
    - v1.1.0: changelogs/v1.1.0.md
    - v1.0.1: changelogs/v1.0.1.md
theme:
  name: null
  custom_dir: 'themes/drycc'
docs_dir: src
markdown_extensions:
  - markdown_checklist.extension
  - markdown_include.include:
      base_path: src/_includes
  - admonition
  - codehilite
  - toc:
      permalink: True
extra_javascript:
  - static/js/foundation.js
  - static/js/foundation.dropdown.js
  - static/js/foundation.offcanvas.js
  - static/js/headroom.min.js
  - static/js/adjustments.js
